export const STRINGS = {
  app: {
    name: 'RevvedUp',
    tagline: "Let's make today's journey memorable",
  },
  home: {
    profileGreeting: 'Welcome back',
    profileName: 'Rider',
    greeting: 'Ready to ride?',
    totalDistance: 'Total Distance',
    totalRides: 'Total Rides',
    explorerScore: 'Explorer Score',
    levelLabel: 'Lv.',
    xpToNext: 'to next level',
    riddenHint: 'ridden · keep exploring',
    recentRides: 'Recent Rides',
    viewAll: 'View All',
    startRide: 'Start Ride',
    noRides: 'No rides yet — your first journey awaits.',
  },
  ride: {
    distance: 'Distance',
    duration: 'Duration',
    speed: 'Speed',
    avgSpeed: 'Avg Speed',
    maxSpeed: 'Max Speed',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    start: 'Start',
    addMemory: 'Add Memory',
    gpsActive: 'GPS Active',
    gpsSearching: 'Searching for GPS…',
    gpsReceiving: 'Acquiring position…',
    gpsDegraded: 'Weak GPS — move or wait',
    gpsLost: 'GPS signal lost',
    savingRide: 'Saving ride…',
    startRideFailedTitle: 'Could not start ride',
    startRideRetry: 'Try again',
    resumeRideTitle: 'Ride in progress',
    resumeRideMessage: 'You have an unsaved ride. Resume recording or discard it?',
    resumeRideConfirm: 'Resume',
    resumeRideDiscard: 'Discard',
    confirmStopTitle: 'End ride?',
    confirmStopMessage: 'Your route and metrics will be saved.',
    confirmStop: 'End Ride',
    cancel: 'Cancel',
    startingRide: 'Starting ride…',
    stopFailedTitle: "Couldn't end ride",
    goHome: 'Go home',
    permissionDeniedTitle: 'Location permission required',
    permissionDeniedMessage:
      'RevvedUp needs your location to track rides. Please enable it in Settings.',
    openSettings: 'Open Settings',
  },
  memory: {
    title: 'Memory Snapshots',
    subtitle: 'Your journey in pictures',
    addTitle: 'Add Memory',
    captionPlaceholder: 'Add a caption (optional)…',
    save: 'Save Memory',
    pickFromGallery: 'Pick from gallery',
    noMemories: 'No memories pinned yet.',
  },
  settings: {
    title: 'Settings',
    back: 'Back',
    general: 'General',
    account: 'Account & profile',
    notifications: 'Notifications',
    privacy: 'Privacy & data',
    about: 'About RevvedUp',
    syncHint:
      'Account sync and cloud backup will connect here in a later release. Your rides stay on this device for now.',
  },
  profile: {
    title: 'Profile & Settings',
    menuSection: 'Account',
    myGarage: 'My Garage',
    emergencyInfo: 'Emergency Information',
    riderGear: 'Rider Gear',
    statRides: 'Rides',
    statDistance: 'Distance',
    statLevel: 'Level',
    signOut: 'Sign out',
    signOutTitle: 'Sign out?',
    signOutMessage:
      'Your ride history stays on this device. Profile, garage, emergency, and gear data will reset to defaults.',
    signOutConfirm: 'Sign out',
    cancel: 'Cancel',
    signedOutTitle: 'Signed out',
    signedOutMessage: 'Profile data was reset. Your rides were not deleted.',
  },
  garage: {
    title: 'My Garage',
    bikesHeading: 'My Bikes',
    primary: 'Primary',
    viewDocuments: 'View documents',
    hideDocuments: 'Hide documents',
    addBike: 'Add bike',
    addBikeTitle: 'Add bike',
    addBikeMessage: 'Adding bikes will be available in a future update.',
    docStatus_valid: 'Valid',
    docStatus_expiring: 'Expiring',
    docStatus_expired: 'Expired',
  },
  emergency: {
    title: 'Emergency Information',
    banner:
      'Critical information for first responders. Keep this up to date before every long ride.',
    contactsTitle: 'Emergency contacts',
    medicalTitle: 'Medical information',
    edit: 'Edit',
    bloodGroup: 'Blood group',
    allergies: 'Allergies',
    medications: 'Medications',
    conditions: 'Conditions',
    editTitle: 'Edit emergency information',
    save: 'Save',
    cancel: 'Cancel',
    placeholderName: 'Name',
    placeholderRelation: 'Relation',
    placeholderPhone: 'Phone',
    placeholderAllergies: 'Comma-separated, e.g. Penicillin, Peanuts',
    placeholderMedications: 'One per line',
    placeholderConditions: 'One per line',
  },
  gear: {
    title: 'Rider Gear',
    equipmentSection: 'Safety equipment',
    intercomSection: 'Intercom system',
    checked: 'Checked',
    battery: 'Battery',
    range: 'Range',
    paired: 'Paired devices',
  },
  history: {
    title: 'Ride History',
    subtitle: 'Your journey chronicles',
    searchPlaceholder: 'Search rides…',
    filterAll: 'All',
    filterSolo: 'Solo',
    filterGroup: 'Group',
    statTotalRides: 'Total Rides',
    statTotalKm: 'Total km',
    statTotalTime: 'Total Time',
    noSearchResults: 'No rides match your search.',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Network error. Check your connection.',
    notFound: 'Not found.',
  },
};
