export const STRINGS = {
  app: {
    name: 'RevvedUp',
    tagline: "Let's make today's journey memorable",
  },
  home: {
    greeting: 'Ready to ride?',
    totalDistance: 'Total Distance',
    totalRides: 'Total Rides',
    explorerScore: 'Explorer Score',
    recentRides: 'Recent Rides',
    viewAll: 'View All',
    startRide: 'Start Ride',
    noRides: 'No rides yet — your first journey awaits.',
  },
  ride: {
    distance: 'Distance',
    duration: 'Duration',
    speed: 'Speed',
    avgSpeed: 'Avg Speed',
    maxSpeed: 'Max Speed',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    start: 'Start',
    addMemory: 'Add Memory',
    gpsActive: 'GPS Active',
    gpsSearching: 'Searching for GPS…',
    gpsLost: 'GPS signal lost',
    confirmStopTitle: 'End ride?',
    confirmStopMessage: 'Your route and metrics will be saved.',
    confirmStop: 'End Ride',
    cancel: 'Cancel',
    permissionDeniedTitle: 'Location permission required',
    permissionDeniedMessage:
      'RevvedUp needs your location to track rides. Please enable it in Settings.',
  },
  memory: {
    title: 'Memory Snapshots',
    subtitle: 'Your journey in pictures',
    addTitle: 'Add Memory',
    captionPlaceholder: 'Add a caption (optional)…',
    save: 'Save Memory',
    pickFromGallery: 'Pick from gallery',
    noMemories: 'No memories pinned yet.',
  },
  history: {
    title: 'Ride History',
    subtitle: 'Your journey chronicles',
    searchPlaceholder: 'Search rides…',
    filterAll: 'All',
    filterSolo: 'Solo',
    filterGroup: 'Group',
    statTotalRides: 'Total Rides',
    statTotalKm: 'Total km',
    statTotalTime: 'Total Time',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Network error. Check your connection.',
    notFound: 'Not found.',
  },
};
